version: '2'

volumes:
  homeassistant-config:

services:
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

  thermostat:
    image: chriszen/homey-thermostat:0.1.1-armhf
    restart: always
    network_mode: "host"
    depends_on:
      - mosquitto
    environment:
      - MQTT_URL=mqtt://mosquitto:1883
      - UI_HREF_URL=index.html

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.80.3
    restart: always
    depends_on:
      - mosquitto
    ports:
      - 8123:8123
    volumes:
      - homeassistant-config:/config

  sensors-hat:
    privileged: true
    build: ./sensors-hat
    restart: always
    depends_on:
      - mosquitto
    environment:
      - MQTT_HOST=mosquitto
      - TEMPERATURE_CORRECTION=-8.0
      - HUMIDITY_CORRECTION=30.0