version: '2'
services:
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

  thermostat:
    image: chriszen/homey-thermostat:0.1.0-armhf
    restart: always
    network_mode: "host"
    environment:
      - MQTT_URL=mqtt://localhost:1883
      - UI_HREF_URL=http://localhost:9000/index.html
    ports:
      - 9000:80

