version: '2'
services:
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

  thermostat:
    image: chriszen/homey-thermostat:0.1.0-armhf
    restart: always
    ports:
      - 8080:80

