version: '2'

volumes:
  homeassistant-config:

services:
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

  thermostat:
    image: chriszen/homey-thermostat:0.1.0-armhf
    restart: always
    network_mode: "host"
    environment:
      - MQTT_URL=mqtt://localhost:1883
      - UI_HREF_URL=http://localhost:9000/index.html

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.80.3
    restart: always
    ports:
      - 8123:80
    volumes:
      - homeassistant-config:/config
